#
# Testing OpenWFE
#
# John Mettraux at openwfe.org
#
# Mon Oct  9 22:19:44 JST 2006
#

#require 'test/unit'

require 'ft_0'
require 'ft_0b_sequence'
require 'ft_0c_testname'
require 'ft_0d_participant'
require 'ft_0e_multibody'
require 'ft_1_unset'
require 'ft_1b_unset'
require 'ft_2_concurrence'
require 'ft_2b_concurrence'
require 'ft_2c_concurrence'
require 'ft_3_equals'
require 'ft_3b_lookup_vf'
require 'ft_4_misc'
require 'ft_6_lambda'
require 'ft_7_lose'
require 'ft_7b_lose'
require 'ft_8_forget'
require 'ft_9_cursor'
require 'ft_9b_cursor'

require 'ft_10_loop'
require 'ft_11_ppd'
require 'ft_11b_ppd'
require 'ft_12_blockparticipant'
require 'ft_14_subprocess'
require 'ft_14b_subprocess'
require 'ft_14c_subprocess'
require 'ft_14d_subprocess'
require 'ft_15_iterator'
require 'ft_15b_iterator'
require 'ft_16_fqv'
require 'ft_17_condition'
require 'ft_18_pname'
require 'extras/ft_19_csv'

require 'ft_22_history'
require 'ft_23_when'
require 'ft_23b_when'
require 'ft_23c_wait'
require 'ft_23d_cww'
require 'ft_24_def'
require 'ft_25_cancel'
require 'ft_27_getflowpos'
require 'ft_28_fileparticipant'

require 'ft_31_flowname'
require 'ft_32_journal'
require 'ft_32c_journal'
require 'ft_32d_journal'
require 'ft_33_description'
require 'ft_34_cancelwfid'
require 'ft_35_localdefs'
require 'ft_36_subprocids'
require 'ft_37_pnames'
require 'ft_38_tag'
require 'ft_38b_tag'
require 'ft_38c_tag'
require 'ft_38d_tag'
require 'ft_39_reserve'
require 'ft_39b_reserve'

require 'ft_40_defined'
require 'ft_41_case'
require 'ft_42_environments'
require 'ft_43_pat10'
require 'ft_44_save'
require 'ft_44b_restore'
require 'ft_45_citerator'
require 'ft_45b_citerator'
require 'ft_46_pparams'
require 'ft_47_filter'
require 'ft_48_fe_filter'
require 'ft_49_condition'

require 'ft_50_xml_attribute'
#require 'ft_51_stack'
require 'ft_52_obs_participant'
require 'ft_53_null_noop_participant'
require 'ft_54_listen'
require 'ft_54b_listen'
require 'ft_54c_listen'
require 'ft_54d_listen'
require 'ft_55_ptimeout'
require 'ft_56_timeout'
require 'ft_57_a'
require 'ft_58_ejournal'
require 'ft_58b_ejournal'
require 'ft_58c_representations'
require 'ft_59_ps'

require 'ft_60_ecancel'
require 'ft_61_elsub'
require 'ft_62_procparticipant'
require 'ft_63_pause'
require 'ft_64_alias'
require 'ft_65_stringlaunch'
require 'ft_66_subforget'
require 'ft_68_ifparticipant'
require 'ft_69_cancelmissing'

require 'ft_70_lookupvar'
require 'ft_71_log'
require 'ft_72_lookup_processes'
require 'ft_73_cancel_sub'
require 'ft_74_block_and_workitem_dup'
require 'ft_75_ruby_attributes'
require 'ft_76_merge_isolate'
require 'ft_77_segments'
require 'ft_78_eval'
require 'ft_79_tticket'
require 'ft_79b_tticket'
require 'ft_79c_outcome'

#require 'back_0916_test' # no backward compatibility with 0.9.16

require 'ft_80_spname'
require 'ft_81_exp'
require 'ft_82_trecu'
require 'ft_84_updateexp'
require 'ft_84b_subrepr'
require 'ft_85_dolhash'
require 'ft_86_dollar_fv'
require 'ft_87_define'
#require 'ft_88_http' # this test requires rufus/verbs
require 'ft_89_polyglot'

require 'ft_90_initial'
require 'ft_91_descendant'
require 'ft_92_varstack'
require 'ft_93_on_error'

