# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruote}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Mettraux", "Kenneth Kalmer"]
  s.date = %q{2009-12-14}
  s.email = %q{jmettraux@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.txt",
     "CREDITS.txt",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "TODO.txt",
     "deps.rip",
     "doc/workflow.txt",
     "doc/wqueue.graffle",
     "examples/flickr_report.rb",
     "examples/ruote_quickstart.rb",
     "lib/ruote.rb",
     "lib/ruote/engine.rb",
     "lib/ruote/engine/context.rb",
     "lib/ruote/engine/engine.rb",
     "lib/ruote/engine/fs_engine.rb",
     "lib/ruote/engine/process_status.rb",
     "lib/ruote/engine/ro_listener.rb",
     "lib/ruote/engine/ro_participant.rb",
     "lib/ruote/engine/ro_wait.rb",
     "lib/ruote/err/ejournal.rb",
     "lib/ruote/err/fs_ejournal.rb",
     "lib/ruote/evt/fs_tracker.rb",
     "lib/ruote/evt/tracker.rb",
     "lib/ruote/exp/command.rb",
     "lib/ruote/exp/condition.rb",
     "lib/ruote/exp/expression_map.rb",
     "lib/ruote/exp/fe_add_branches.rb",
     "lib/ruote/exp/fe_apply.rb",
     "lib/ruote/exp/fe_cancel_process.rb",
     "lib/ruote/exp/fe_command.rb",
     "lib/ruote/exp/fe_concurrence.rb",
     "lib/ruote/exp/fe_concurrent_iterator.rb",
     "lib/ruote/exp/fe_cron.rb",
     "lib/ruote/exp/fe_cursor.rb",
     "lib/ruote/exp/fe_define.rb",
     "lib/ruote/exp/fe_echo.rb",
     "lib/ruote/exp/fe_equals.rb",
     "lib/ruote/exp/fe_error.rb",
     "lib/ruote/exp/fe_forget.rb",
     "lib/ruote/exp/fe_if.rb",
     "lib/ruote/exp/fe_inc.rb",
     "lib/ruote/exp/fe_iterator.rb",
     "lib/ruote/exp/fe_listen.rb",
     "lib/ruote/exp/fe_noop.rb",
     "lib/ruote/exp/fe_participant.rb",
     "lib/ruote/exp/fe_redo.rb",
     "lib/ruote/exp/fe_reserve.rb",
     "lib/ruote/exp/fe_restore.rb",
     "lib/ruote/exp/fe_save.rb",
     "lib/ruote/exp/fe_sequence.rb",
     "lib/ruote/exp/fe_set.rb",
     "lib/ruote/exp/fe_subprocess.rb",
     "lib/ruote/exp/fe_undo.rb",
     "lib/ruote/exp/fe_wait.rb",
     "lib/ruote/exp/fe_when.rb",
     "lib/ruote/exp/flowexpression.rb",
     "lib/ruote/exp/iterator.rb",
     "lib/ruote/exp/merge.rb",
     "lib/ruote/exp/raw.rb",
     "lib/ruote/exp/ro_attributes.rb",
     "lib/ruote/exp/ro_tickets.rb",
     "lib/ruote/exp/ro_variables.rb",
     "lib/ruote/fei.rb",
     "lib/ruote/launchitem.rb",
     "lib/ruote/log/fs_history.rb",
     "lib/ruote/log/logger.rb",
     "lib/ruote/log/test_logger.rb",
     "lib/ruote/parser.rb",
     "lib/ruote/parser/ruby_dsl.rb",
     "lib/ruote/parser/xml.rb",
     "lib/ruote/part/block_participant.rb",
     "lib/ruote/part/fs_participant.rb",
     "lib/ruote/part/hash_participant.rb",
     "lib/ruote/part/local_participant.rb",
     "lib/ruote/part/no_op_participant.rb",
     "lib/ruote/part/null_participant.rb",
     "lib/ruote/part/participant_list.rb",
     "lib/ruote/part/smtp_participant.rb",
     "lib/ruote/part/template.rb",
     "lib/ruote/pool/errors.rb",
     "lib/ruote/pool/expression_pool.rb",
     "lib/ruote/pool/mnemo_wfid_generator.rb",
     "lib/ruote/pool/wfid_generator.rb",
     "lib/ruote/queue/em_workqueue.rb",
     "lib/ruote/queue/fiber_workqueue.rb",
     "lib/ruote/queue/subscriber.rb",
     "lib/ruote/queue/thread_workqueue.rb",
     "lib/ruote/queue/workqueue.rb",
     "lib/ruote/storage/base.rb",
     "lib/ruote/storage/cache_storage.rb",
     "lib/ruote/storage/fs_storage.rb",
     "lib/ruote/storage/hash_storage.rb",
     "lib/ruote/time/fs_scheduler.rb",
     "lib/ruote/time/scheduler.rb",
     "lib/ruote/tree_dot.rb",
     "lib/ruote/util/bucket.rb",
     "lib/ruote/util/dollar.rb",
     "lib/ruote/util/jash.rb",
     "lib/ruote/util/json.rb",
     "lib/ruote/util/lookup.rb",
     "lib/ruote/util/mem.rb",
     "lib/ruote/util/misc.rb",
     "lib/ruote/util/ometa.rb",
     "lib/ruote/util/serializer.rb",
     "lib/ruote/util/tree.rb",
     "lib/ruote/util/treechecker.rb",
     "lib/ruote/workitem.rb",
     "mruby.rb",
     "ruote.gemspec",
     "test/README.rdoc",
     "test/bm/ci.rb",
     "test/bm/ici.rb",
     "test/bm/jash.rb",
     "test/bm/juuman.rb",
     "test/bm/load_26c.rb",
     "test/bm/t.rb",
     "test/functional/base.rb",
     "test/functional/ct_0_concurrence.rb",
     "test/functional/eft_0_process_definition.rb",
     "test/functional/eft_10_cancel_process.rb",
     "test/functional/eft_11_wait.rb",
     "test/functional/eft_12_listen.rb",
     "test/functional/eft_13_iterator.rb",
     "test/functional/eft_14_cursor.rb",
     "test/functional/eft_15_loop.rb",
     "test/functional/eft_16_if.rb",
     "test/functional/eft_17_equals.rb",
     "test/functional/eft_18_concurrent_iterator.rb",
     "test/functional/eft_19_reserve.rb",
     "test/functional/eft_1_echo.rb",
     "test/functional/eft_20_save.rb",
     "test/functional/eft_21_restore.rb",
     "test/functional/eft_22_noop.rb",
     "test/functional/eft_23_apply.rb",
     "test/functional/eft_24_add_branches.rb",
     "test/functional/eft_25_command.rb",
     "test/functional/eft_26_error.rb",
     "test/functional/eft_27_inc.rb",
     "test/functional/eft_28_when.rb",
     "test/functional/eft_29_cron.rb",
     "test/functional/eft_2_sequence.rb",
     "test/functional/eft_3_participant.rb",
     "test/functional/eft_4_set.rb",
     "test/functional/eft_5_subprocess.rb",
     "test/functional/eft_6_concurrence.rb",
     "test/functional/eft_7_forget.rb",
     "test/functional/eft_8_undo.rb",
     "test/functional/eft_9_redo.rb",
     "test/functional/engine_helper.rb",
     "test/functional/ft_0_wqueue.rb",
     "test/functional/ft_10_dollar.rb",
     "test/functional/ft_11_recursion.rb",
     "test/functional/ft_12_launchitem.rb",
     "test/functional/ft_13_variables.rb",
     "test/functional/ft_14_re_apply.rb",
     "test/functional/ft_15_timeout.rb",
     "test/functional/ft_16_participant_params.rb",
     "test/functional/ft_17_conditional.rb",
     "test/functional/ft_18_kill.rb",
     "test/functional/ft_19_alias.rb",
     "test/functional/ft_1_process_status.rb",
     "test/functional/ft_20_fs_participant.rb",
     "test/functional/ft_21_forget.rb",
     "test/functional/ft_22_process_definitions.rb",
     "test/functional/ft_23_load_defs.rb",
     "test/functional/ft_24_block_participants.rb",
     "test/functional/ft_25_listener_registration.rb",
     "test/functional/ft_26_participant_timeout.rb",
     "test/functional/ft_27_var_indirection.rb",
     "test/functional/ft_28_null_noop_participants.rb",
     "test/functional/ft_29_part_template.rb",
     "test/functional/ft_2_errors.rb",
     "test/functional/ft_30_smtp_participant.rb",
     "test/functional/ft_31_part_blocking.rb",
     "test/functional/ft_32_history.rb",
     "test/functional/ft_33_participant_subprocess_priority.rb",
     "test/functional/ft_34_cursor_rewind.rb",
     "test/functional/ft_3_participant_registration.rb",
     "test/functional/ft_4_cancel.rb",
     "test/functional/ft_5_on_error.rb",
     "test/functional/ft_6_on_cancel.rb",
     "test/functional/ft_7_tags.rb",
     "test/functional/ft_8_participant_consumption.rb",
     "test/functional/ft_9_subprocesses.rb",
     "test/functional/restart_base.rb",
     "test/functional/rt_0_wait.rb",
     "test/functional/rt_1_listen.rb",
     "test/functional/rt_2_errors.rb",
     "test/functional/rt_3_when.rb",
     "test/functional/rt_4_cron.rb",
     "test/functional/rt_5_timeout.rb",
     "test/functional/rtest.rb",
     "test/functional/test.rb",
     "test/mpc_test.rb",
     "test/path_helper.rb",
     "test/pdef.xml",
     "test/test.rb",
     "test/test_helper.rb",
     "test/unit/test.rb",
     "test/unit/ut_0_ruby_parser.rb",
     "test/unit/ut_10_json.rb",
     "test/unit/ut_11_lookup.rb",
     "test/unit/ut_12_jash.rb",
     "test/unit/ut_13_serializer.rb",
     "test/unit/ut_14_is_uri.rb",
     "test/unit/ut_15_util.rb",
     "test/unit/ut_16_parser.rb",
     "test/unit/ut_1_fei.rb",
     "test/unit/ut_2_wfidgen.rb",
     "test/unit/ut_4_expmap.rb",
     "test/unit/ut_5_tree.rb",
     "test/unit/ut_6_condition.rb",
     "test/unit/ut_7_workitem.rb",
     "test/unit/ut_8_tree_to_dot.rb",
     "test/unit/ut_9_xml_parser.rb"
  ]
  s.homepage = %q{http://ruote.rubyforge.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{openwferu}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{an open source ruby workflow engine}
  s.test_files = [
    "test/test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rufus-lru>, [">= 0"])
      s.add_runtime_dependency(%q<rufus-scheduler>, ["= 2.0.1"])
      s.add_runtime_dependency(%q<rufus-dollar>, [">= 0"])
      s.add_runtime_dependency(%q<rufus-treechecker>, ["= 1.0.3"])
      s.add_runtime_dependency(%q<rufus-mnemo>, ["= 1.1.0"])
      s.add_runtime_dependency(%q<rufus-verbs>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rufus-lru>, [">= 0"])
      s.add_dependency(%q<rufus-scheduler>, ["= 2.0.1"])
      s.add_dependency(%q<rufus-dollar>, [">= 0"])
      s.add_dependency(%q<rufus-treechecker>, ["= 1.0.3"])
      s.add_dependency(%q<rufus-mnemo>, ["= 1.1.0"])
      s.add_dependency(%q<rufus-verbs>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rufus-lru>, [">= 0"])
    s.add_dependency(%q<rufus-scheduler>, ["= 2.0.1"])
    s.add_dependency(%q<rufus-dollar>, [">= 0"])
    s.add_dependency(%q<rufus-treechecker>, ["= 1.0.3"])
    s.add_dependency(%q<rufus-mnemo>, ["= 1.1.0"])
    s.add_dependency(%q<rufus-verbs>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

